import { LendingPool } from "../types/defi";

export const COIN_METADATA: Record<string, { icon: string; badge?: string }> = {
  SUI: { icon: "🔵" },
  USDC: { icon: "💵" },
  sbUSDT: { icon: "💰", badge: "Sui Bridge" },
  sbETH: { icon: "💎", badge: "Sui Bridge" },
  USDY: { icon: "💲" },
  WAL: { icon: "🌊" },
  SCA: { icon: "⚡" },
  DEEP: { icon: "🌀" },
  CETUS: { icon: "🐙" },
  afSUI: { icon: "💧" },
  haSUI: { icon: "🔥" },
  vSUI: { icon: "🍇" },
  FUD: { icon: "🍄" },
  BLUB: { icon: "🐟" },
  mUSD: { icon: "💶" },
  NS: { icon: "🏷️" },
  wWAL: { icon: "🌪️" },
  haWAL: { icon: "💨" },
  haedal: { icon: "🦦" },
  fdusd: { icon: "📉" },
};

export const getCoinMetadata = (symbol: string) => {
  return COIN_METADATA[symbol] || { icon: symbol[0] };
};

export const LENDING_POOLS_DATA: LendingPool[] = [
  {
    coin: "SUI",
    icon: "🔵",
    price: 1.7,
    yourSupply: 0,
    totalSupply: 6540000,
    totalBorrow: 3390000,
    utilizationRate: 51.86,
    apy: 3.48,
  },
  {
    coin: "USDC",
    icon: "💵",
    price: 0.99,
    yourSupply: 0,
    totalSupply: 7450000,
    totalBorrow: 5730000,
    utilizationRate: 76.89,
    apy: 5.91,
  },
  {
    coin: "sbUSDT",
    icon: "💰",
    price: 0.99,
    yourSupply: 0,
    totalSupply: 2520000,
    totalBorrow: 2070000,
    utilizationRate: 82.35,
    apy: 6.66,
    badge: "Sui Bridge",
  },
  {
    coin: "sbETH",
    icon: "💎",
    price: 3294.96,
    yourSupply: 0,
    totalSupply: 588150,
    totalBorrow: 364850,
    utilizationRate: 62.03,
    apy: 4.5,
    badge: "Sui Bridge",
  },
  {
    coin: "USDY",
    icon: "💲",
    price: 1.12,
    yourSupply: 0,
    totalSupply: 1070000,
    totalBorrow: 816740,
    utilizationRate: 75.69,
    apy: 5.75,
  },
  {
    coin: "WAL",
    icon: "🌊",
    price: 0.15878,
    yourSupply: 0,
    totalSupply: 5860000,
    totalBorrow: 5020000,
    utilizationRate: 85.7,
    apy: 28.19,
  },
  {
    coin: "SCA",
    icon: "⚡",
    price: 0.043,
    yourSupply: 0,
    totalSupply: 9960000,
    totalBorrow: 5280000,
    utilizationRate: 53.02,
    apy: 15,
  },
  {
    coin: "DEEP",
    icon: "🌀",
    price: 0.04867,
    yourSupply: 0,
    totalSupply: 8590000,
    totalBorrow: 6040000,
    utilizationRate: 70.29,
    apy: 15.21,
  },
];
